services:
  Ivanstan\SymfonySupport\EventSubscriber\ApiExceptionSubscriber:
    arguments: ['@parameter_bag']
    tags:
      - { name: kernel.event_subscriber }

  Ivanstan\SymfonySupport\Command\DoctrineReloadCommand:
    arguments: ['@parameter_bag']
    tags:
      - { name: console.command }

  Ivanstan\SymfonySupport\:
    resource: '../../'
    autowire: true
    autoconfigure: true
