services:
  Ivanstan\SymfonyRest\EventSubscriber\ApiExceptionSubscriber:
    arguments: ['@parameter_bag']
    tags:
      - { name: kernel.event_subscriber }

  Ivanstan\SymfonyRest\Command\DoctrineReloadCommand:
    arguments: ['@parameter_bag']
    tags:
      - { name: console.command }

  Ivanstan\SymfonyRest\:
    resource: '../../'
    autowire: true
    autoconfigure: true
