services:
  Ivanstan\SymfonySupport\:
    resource: '../../*'
    autowire: true
    autoconfigure: true

  Ivanstan\SymfonySupport\EventSubscriber\ApiExceptionSubscriber:
    arguments: ['@parameter_bag']
    tags:
      - { name: kernel.event_subscriber }
