services:
  Ivanstan\SymfonyRest\EventSubscriber\ApiExceptionSubscriber:
    arguments: ['@parameter_bag']
    tags:
      - { name: kernel.event_subscriber }

  Ivanstan\SymfonyRest\Command:
    resource: '../../AppBundle/Command/*'
    tags: ['console.command']
